server:
  port: 8080
  servlet:
    session:
      timeout: 5m # 设置session的有效期为五分钟
  compression:
    enabled: true # 开启返回结果压缩，减少传输耗时
    min-response-size: 2KB

# 引入其他 yaml 文件配置
spring:
  config:
    import: application-dal.yml

# knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: TGR-FileSharing
    description: 基于 REACT + SPRINGBOOT 开发的文件共享系统
    version: 1.0.0
    concat:
      - tjyy
      - https://github.com/Tjyy-1223/TGR-FileSharing
    license: Apache License 2.0
    license-url:
    email: tjyy24@nuaa.edu.cn
    group:
      front:
        group-name: 相关功能实现
        api-rule: package
        api-rule-resources:
          - com.tjyy.sharing.web.front

# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

# 默认的数据库名
database:
  name: file_sharing